FROM ubi9-minimal as build

ARG MODEL_ORG
ARG MODEL_NAME
ARG HF_TOKEN
ARG EXCLUDE_FILES=".git/"
ARG MODEL_SIZE="32000"

RUN echo "MODEL_ORG: $MODEL_ORG, MODEL_NAME: $MODEL_NAME"
RUN echo "HF_TOKEN hash: $(echo $HF_TOKEN | sha256sum)"

RUN mkdir model
RUN dd if=/dev/zero of=model/fake_model.bin  bs=1M  count=$MODEL_SIZE

FROM ubi9-minimal as models
RUN mkdir /models
COPY --from=build model/* /models
RUN ls -lh /models/
