FROM ubi9-minimal as build

ARG MODEL_ORG
ARG MODEL_NAME
ARG HF_USER
ARG HF_TOKEN

RUN microdnf -y install git git-lfs python3 python3-pip
RUN pip install -U "huggingface_hub[cli]"

RUN echo "MODEL_ORG: $MODEL_ORG, MODEL_NAME: $MODEL_NAME"
RUN echo "Token: $HF_TOKEN"

RUN huggingface-cli login --token $HF_TOKEN
RUN huggingface-cli download $MODEL_ORG/$MODEL_NAME --local-dir model

FROM ubi9-minimal as models
RUN mkdir /models
COPY --from=build model/* /models
